// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("YC.Web")>]
[<assembly: AssemblyProductAttribute("YC.Web")>]
[<assembly: AssemblyDescriptionAttribute("Web UI for YC")>]
[<assembly: AssemblyVersionAttribute("1.0.1")>]
[<assembly: AssemblyFileVersionAttribute("1.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "YC.Web"
    let [<Literal>] AssemblyProduct = "YC.Web"
    let [<Literal>] AssemblyDescription = "Web UI for YC"
    let [<Literal>] AssemblyVersion = "1.0.1"
    let [<Literal>] AssemblyFileVersion = "1.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
